//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeightScale.CacheApi.SoapProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="SoapProxy.WeightScaleServiceSoap")]
    public interface WeightScaleServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.GetAllMeasurementRequests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeightScale.CacheApi.SoapProxy.SoapMessage[] GetAllMeasurementRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.GetAllMeasurementRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<WeightScale.CacheApi.SoapProxy.SoapMessage[]> GetAllMeasurementRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.InsertMeasurementResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeightScale.CacheApi.SoapProxy.CValidationMessage[] InsertMeasurementResult(WeightScale.CacheApi.SoapProxy.SoapMessage inResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.InsertMeasurementResult", ReplyAction="*")]
        System.Threading.Tasks.Task<WeightScale.CacheApi.SoapProxy.CValidationMessage[]> InsertMeasurementResultAsync(WeightScale.CacheApi.SoapProxy.SoapMessage inResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.Test", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.Transport1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Transport1(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageNew input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.Transport1", ReplyAction="*")]
        System.Threading.Tasks.Task Transport1Async(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageNew input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.Transport2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Transport2(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageOld input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SWT.WeightScaleService.Transport2", ReplyAction="*")]
        System.Threading.Tasks.Task Transport2Async(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageOld input);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class SoapMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string uRLField;
        
        private CWeigthScaleMessageBase messageField;
        
        private CValidationMessage[] validationMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CWeigthScaleMessageBase Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public CValidationMessage[] ValidationMessages {
            get {
                return this.validationMessagesField;
            }
            set {
                this.validationMessagesField = value;
                this.RaisePropertyChanged("ValidationMessages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public abstract partial class CWeigthScaleMessageBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class CWeigthScaleMessageOld : CWeigthScaleMessageBase, System.ComponentModel.INotifyPropertyChanged {
        
        private long numberField;
        
        private bool numberFieldSpecified;
        
        private long directionField;
        
        private bool directionFieldSpecified;
        
        private string timeOfFirstMeasureField;
        
        private string timeOfSecondMeasureField;
        
        private long measurementStatusField;
        
        private bool measurementStatusFieldSpecified;
        
        private long serialNumberField;
        
        private bool serialNumberFieldSpecified;
        
        private long transactionNumberField;
        
        private bool transactionNumberFieldSpecified;
        
        private long measurementNumberField;
        
        private bool measurementNumberFieldSpecified;
        
        private long productCodeField;
        
        private bool productCodeFieldSpecified;
        
        private string productNameField;
        
        private long tareWeightField;
        
        private bool tareWeightFieldSpecified;
        
        private long grossWeightField;
        
        private bool grossWeightFieldSpecified;
        
        private long netWeightField;
        
        private bool netWeightFieldSpecified;
        
        private long totalOfGrossWeightField;
        
        private bool totalOfGrossWeightFieldSpecified;
        
        private long totalOfNetWeightField;
        
        private bool totalOfNetWeightFieldSpecified;
        
        private string vehicleField;
        
        private long documentNumberField;
        
        private bool documentNumberFieldSpecified;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("NumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectionSpecified {
            get {
                return this.directionFieldSpecified;
            }
            set {
                this.directionFieldSpecified = value;
                this.RaisePropertyChanged("DirectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TimeOfFirstMeasure {
            get {
                return this.timeOfFirstMeasureField;
            }
            set {
                this.timeOfFirstMeasureField = value;
                this.RaisePropertyChanged("TimeOfFirstMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TimeOfSecondMeasure {
            get {
                return this.timeOfSecondMeasureField;
            }
            set {
                this.timeOfSecondMeasureField = value;
                this.RaisePropertyChanged("TimeOfSecondMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long MeasurementStatus {
            get {
                return this.measurementStatusField;
            }
            set {
                this.measurementStatusField = value;
                this.RaisePropertyChanged("MeasurementStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeasurementStatusSpecified {
            get {
                return this.measurementStatusFieldSpecified;
            }
            set {
                this.measurementStatusFieldSpecified = value;
                this.RaisePropertyChanged("MeasurementStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SerialNumberSpecified {
            get {
                return this.serialNumberFieldSpecified;
            }
            set {
                this.serialNumberFieldSpecified = value;
                this.RaisePropertyChanged("SerialNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
                this.RaisePropertyChanged("TransactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionNumberSpecified {
            get {
                return this.transactionNumberFieldSpecified;
            }
            set {
                this.transactionNumberFieldSpecified = value;
                this.RaisePropertyChanged("TransactionNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long MeasurementNumber {
            get {
                return this.measurementNumberField;
            }
            set {
                this.measurementNumberField = value;
                this.RaisePropertyChanged("MeasurementNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeasurementNumberSpecified {
            get {
                return this.measurementNumberFieldSpecified;
            }
            set {
                this.measurementNumberFieldSpecified = value;
                this.RaisePropertyChanged("MeasurementNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductCodeSpecified {
            get {
                return this.productCodeFieldSpecified;
            }
            set {
                this.productCodeFieldSpecified = value;
                this.RaisePropertyChanged("ProductCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long TareWeight {
            get {
                return this.tareWeightField;
            }
            set {
                this.tareWeightField = value;
                this.RaisePropertyChanged("TareWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TareWeightSpecified {
            get {
                return this.tareWeightFieldSpecified;
            }
            set {
                this.tareWeightFieldSpecified = value;
                this.RaisePropertyChanged("TareWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long GrossWeight {
            get {
                return this.grossWeightField;
            }
            set {
                this.grossWeightField = value;
                this.RaisePropertyChanged("GrossWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossWeightSpecified {
            get {
                return this.grossWeightFieldSpecified;
            }
            set {
                this.grossWeightFieldSpecified = value;
                this.RaisePropertyChanged("GrossWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
                this.RaisePropertyChanged("NetWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetWeightSpecified {
            get {
                return this.netWeightFieldSpecified;
            }
            set {
                this.netWeightFieldSpecified = value;
                this.RaisePropertyChanged("NetWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long TotalOfGrossWeight {
            get {
                return this.totalOfGrossWeightField;
            }
            set {
                this.totalOfGrossWeightField = value;
                this.RaisePropertyChanged("TotalOfGrossWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOfGrossWeightSpecified {
            get {
                return this.totalOfGrossWeightFieldSpecified;
            }
            set {
                this.totalOfGrossWeightFieldSpecified = value;
                this.RaisePropertyChanged("TotalOfGrossWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long TotalOfNetWeight {
            get {
                return this.totalOfNetWeightField;
            }
            set {
                this.totalOfNetWeightField = value;
                this.RaisePropertyChanged("TotalOfNetWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalOfNetWeightSpecified {
            get {
                return this.totalOfNetWeightFieldSpecified;
            }
            set {
                this.totalOfNetWeightFieldSpecified = value;
                this.RaisePropertyChanged("TotalOfNetWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
                this.RaisePropertyChanged("Vehicle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public long DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentNumberSpecified {
            get {
                return this.documentNumberFieldSpecified;
            }
            set {
                this.documentNumberFieldSpecified = value;
                this.RaisePropertyChanged("DocumentNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class CWeigthScaleMessageNew : CWeigthScaleMessageBase, System.ComponentModel.INotifyPropertyChanged {
        
        private long numberField;
        
        private bool numberFieldSpecified;
        
        private long directionField;
        
        private bool directionFieldSpecified;
        
        private string timeOfFirstMeasureField;
        
        private string timeOfSecondMeasureField;
        
        private long measurementStatusField;
        
        private bool measurementStatusFieldSpecified;
        
        private long serialNumberField;
        
        private bool serialNumberFieldSpecified;
        
        private long transactionNumberField;
        
        private bool transactionNumberFieldSpecified;
        
        private long measurementNumberField;
        
        private bool measurementNumberFieldSpecified;
        
        private long productCodeField;
        
        private bool productCodeFieldSpecified;
        
        private string exciseDocumentNumberField;
        
        private long tareWeightField;
        
        private bool tareWeightFieldSpecified;
        
        private long grossWeightField;
        
        private bool grossWeightFieldSpecified;
        
        private long netWeightField;
        
        private bool netWeightFieldSpecified;
        
        private long totalNetOfInputField;
        
        private bool totalNetOfInputFieldSpecified;
        
        private long totalNetOfOutputField;
        
        private bool totalNetOfOutputFieldSpecified;
        
        private string vehicleField;
        
        private string documentNumberField;
        
        private long totalNetByProductInputField;
        
        private bool totalNetByProductInputFieldSpecified;
        
        private long totalNetByProductOutputField;
        
        private bool totalNetByProductOutputFieldSpecified;
        
        private long statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("NumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectionSpecified {
            get {
                return this.directionFieldSpecified;
            }
            set {
                this.directionFieldSpecified = value;
                this.RaisePropertyChanged("DirectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TimeOfFirstMeasure {
            get {
                return this.timeOfFirstMeasureField;
            }
            set {
                this.timeOfFirstMeasureField = value;
                this.RaisePropertyChanged("TimeOfFirstMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TimeOfSecondMeasure {
            get {
                return this.timeOfSecondMeasureField;
            }
            set {
                this.timeOfSecondMeasureField = value;
                this.RaisePropertyChanged("TimeOfSecondMeasure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long MeasurementStatus {
            get {
                return this.measurementStatusField;
            }
            set {
                this.measurementStatusField = value;
                this.RaisePropertyChanged("MeasurementStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeasurementStatusSpecified {
            get {
                return this.measurementStatusFieldSpecified;
            }
            set {
                this.measurementStatusFieldSpecified = value;
                this.RaisePropertyChanged("MeasurementStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SerialNumberSpecified {
            get {
                return this.serialNumberFieldSpecified;
            }
            set {
                this.serialNumberFieldSpecified = value;
                this.RaisePropertyChanged("SerialNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
                this.RaisePropertyChanged("TransactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionNumberSpecified {
            get {
                return this.transactionNumberFieldSpecified;
            }
            set {
                this.transactionNumberFieldSpecified = value;
                this.RaisePropertyChanged("TransactionNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long MeasurementNumber {
            get {
                return this.measurementNumberField;
            }
            set {
                this.measurementNumberField = value;
                this.RaisePropertyChanged("MeasurementNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeasurementNumberSpecified {
            get {
                return this.measurementNumberFieldSpecified;
            }
            set {
                this.measurementNumberFieldSpecified = value;
                this.RaisePropertyChanged("MeasurementNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductCodeSpecified {
            get {
                return this.productCodeFieldSpecified;
            }
            set {
                this.productCodeFieldSpecified = value;
                this.RaisePropertyChanged("ProductCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ExciseDocumentNumber {
            get {
                return this.exciseDocumentNumberField;
            }
            set {
                this.exciseDocumentNumberField = value;
                this.RaisePropertyChanged("ExciseDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long TareWeight {
            get {
                return this.tareWeightField;
            }
            set {
                this.tareWeightField = value;
                this.RaisePropertyChanged("TareWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TareWeightSpecified {
            get {
                return this.tareWeightFieldSpecified;
            }
            set {
                this.tareWeightFieldSpecified = value;
                this.RaisePropertyChanged("TareWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long GrossWeight {
            get {
                return this.grossWeightField;
            }
            set {
                this.grossWeightField = value;
                this.RaisePropertyChanged("GrossWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossWeightSpecified {
            get {
                return this.grossWeightFieldSpecified;
            }
            set {
                this.grossWeightFieldSpecified = value;
                this.RaisePropertyChanged("GrossWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
                this.RaisePropertyChanged("NetWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetWeightSpecified {
            get {
                return this.netWeightFieldSpecified;
            }
            set {
                this.netWeightFieldSpecified = value;
                this.RaisePropertyChanged("NetWeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long TotalNetOfInput {
            get {
                return this.totalNetOfInputField;
            }
            set {
                this.totalNetOfInputField = value;
                this.RaisePropertyChanged("TotalNetOfInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalNetOfInputSpecified {
            get {
                return this.totalNetOfInputFieldSpecified;
            }
            set {
                this.totalNetOfInputFieldSpecified = value;
                this.RaisePropertyChanged("TotalNetOfInputSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long TotalNetOfOutput {
            get {
                return this.totalNetOfOutputField;
            }
            set {
                this.totalNetOfOutputField = value;
                this.RaisePropertyChanged("TotalNetOfOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalNetOfOutputSpecified {
            get {
                return this.totalNetOfOutputFieldSpecified;
            }
            set {
                this.totalNetOfOutputFieldSpecified = value;
                this.RaisePropertyChanged("TotalNetOfOutputSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
                this.RaisePropertyChanged("Vehicle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("DocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long TotalNetByProductInput {
            get {
                return this.totalNetByProductInputField;
            }
            set {
                this.totalNetByProductInputField = value;
                this.RaisePropertyChanged("TotalNetByProductInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalNetByProductInputSpecified {
            get {
                return this.totalNetByProductInputFieldSpecified;
            }
            set {
                this.totalNetByProductInputFieldSpecified = value;
                this.RaisePropertyChanged("TotalNetByProductInputSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long TotalNetByProductOutput {
            get {
                return this.totalNetByProductOutputField;
            }
            set {
                this.totalNetByProductOutputField = value;
                this.RaisePropertyChanged("TotalNetByProductOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalNetByProductOutputSpecified {
            get {
                return this.totalNetByProductOutputFieldSpecified;
            }
            set {
                this.totalNetByProductOutputFieldSpecified = value;
                this.RaisePropertyChanged("TotalNetByProductOutputSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class CValidationMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long typeField;
        
        private bool typeFieldSpecified;
        
        private string fieldField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeightScaleServiceSoapChannel : WeightScale.CacheApi.SoapProxy.WeightScaleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeightScaleServiceSoapClient : System.ServiceModel.ClientBase<WeightScale.CacheApi.SoapProxy.WeightScaleServiceSoap>, WeightScale.CacheApi.SoapProxy.WeightScaleServiceSoap {
        
        public WeightScaleServiceSoapClient() {
        }
        
        public WeightScaleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeightScaleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeightScaleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeightScaleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WeightScale.CacheApi.SoapProxy.SoapMessage[] GetAllMeasurementRequests() {
            return base.Channel.GetAllMeasurementRequests();
        }
        
        public System.Threading.Tasks.Task<WeightScale.CacheApi.SoapProxy.SoapMessage[]> GetAllMeasurementRequestsAsync() {
            return base.Channel.GetAllMeasurementRequestsAsync();
        }
        
        public WeightScale.CacheApi.SoapProxy.CValidationMessage[] InsertMeasurementResult(WeightScale.CacheApi.SoapProxy.SoapMessage inResult) {
            return base.Channel.InsertMeasurementResult(inResult);
        }
        
        public System.Threading.Tasks.Task<WeightScale.CacheApi.SoapProxy.CValidationMessage[]> InsertMeasurementResultAsync(WeightScale.CacheApi.SoapProxy.SoapMessage inResult) {
            return base.Channel.InsertMeasurementResultAsync(inResult);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public void Transport1(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageNew input) {
            base.Channel.Transport1(input);
        }
        
        public System.Threading.Tasks.Task Transport1Async(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageNew input) {
            return base.Channel.Transport1Async(input);
        }
        
        public void Transport2(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageOld input) {
            base.Channel.Transport2(input);
        }
        
        public System.Threading.Tasks.Task Transport2Async(WeightScale.CacheApi.SoapProxy.CWeigthScaleMessageOld input) {
            return base.Channel.Transport2Async(input);
        }
    }
}
